pandoc intro.md -o courspdf/introduction.pdf
pandoc selectionsort.md -o courspdf/tris/selectionsort.pdf
pandoc quicksort.md -o courspdf/tris/quicksort.pdf
pandoc recherche_tableau.md -o courspdf/recherche/recherches_dans_tableau.pdf
pandoc fibonaci.md -o courspdf/multiplications_et_Fibonaci.pdf
pandoc systeme_formel.md -o courspdf/systeme_formel_axiomes.pdf
pandoc complexite.md -o courspdf/complexite_d_un_programme.pdf
pandoc heapsort.md -o courspdf/tris/heapsort.pdf
pandoc mergesort.md -o courspdf/tris/mergesort.pdf
pandoc pieme_valeur_tab.md -o courspdf/recherche/pieme_valeur_d_un_tableau.pdf
pandoc dynamique_intro.md -o courspdf/programmation-dynamique/introduction.pdf
pandoc struct_donnee.md -o courspdf/programmation-dynamique/structures_donnees.pdf
