pandoc coursmd/intro.md -o courspdf/introduction.pdf
pandoc coursmd/selectionsort.md -o courspdf/tris/selectionsort.pdf
pandoc coursmd/quicksort.md -o courspdf/tris/quicksort.pdf
pandoc coursmd/recherche_tableau.md -o courspdf/recherche/recherches_dans_tableau.pdf
pandoc coursmd/fibonaci.md -o courspdf/multiplications_et_Fibonaci.pdf
pandoc coursmd/systeme_formel.md -o courspdf/systeme_formel_axiomes.pdf
pandoc coursmd/complexite.md -o courspdf/complexite_d_un_programme.pdf
pandoc coursmd/heapsort.md -o courspdf/tris/heapsort.pdf
pandoc coursmd/mergesort.md -o courspdf/tris/mergesort.pdf
pandoc coursmd/pieme_valeur_tab.md -o courspdf/recherche/pieme_valeur_d_un_tableau.pdf
pandoc coursmd/dynamique_intro.md -o courspdf/programmation-dynamique/introduction.pdf
pandoc coursmd/struct_donnee.md -o courspdf/programmation-dynamique/structures_donnees.pdf
pandoc coursmd/arbre_binaire.md -o courspdf/programmation-dynamique/arbre_binaire.pdf
pandoc coursmd/arbres_recherche.md -o courspdf/programmation-dynamique/arbres_recherche.pdf
pandoc coursmd/fret_cout_min.md -o courspdf/programmation-dynamique/fret_cout_min.pdf
pandoc coursmd/longue_sequence_commune.md -o courspdf/programmation-dynamique/longue_sequence_commune.pdf
pandoc coursmd/ordonnancement_optimal.md -o courspdf/programmation-dynamique/ordonnancement_optimal.pdf
